### ISSUE TITLE
Can't extract parameters DCB and DCB_Error from TEC products

### ISSUE THREAD

**Issue by lmar76** [miktoki/swtools#2]
It is not possible to get "DCB" and "DCB_Error" parameters from TEC products. E.g.:

```python
>>> import swarmtoolkit as st
>>> cdf = 'SW_OPER_TECATMS_2F_20170201T000000_20170201T235959_0202.cdf'
>>> st.getCDFparams(cdf, 'DCB')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luca/.local/opt/anaconda3/lib/python3.6/site-packages/swarmtoolkit-1.2.3-py3.6.egg/swarmtoolkit/sw_io.py", line 104, in getCDFparams
    p_out.append(extract_parameter(cdflist,par,**kwargs))
  File "/home/luca/.local/opt/anaconda3/lib/python3.6/site-packages/swarmtoolkit-1.2.3-py3.6.egg/swarmtoolkit/sw_io.py", line 596, in extract_parameter
    if values[0] is not None:
IndexError: too many indices for array
>>> st.getCDFparams(cdf, 'DCB_Error')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luca/.local/opt/anaconda3/lib/python3.6/site-packages/swarmtoolkit-1.2.3-py3.6.egg/swarmtoolkit/sw_io.py", line 104, in getCDFparams
    p_out.append(extract_parameter(cdflist,par,**kwargs))
  File "/home/luca/.local/opt/anaconda3/lib/python3.6/site-packages/swarmtoolkit-1.2.3-py3.6.egg/swarmtoolkit/sw_io.py", line 596, in extract_parameter
    if values[0] is not None:
IndexError: too many indices for array
>>> st.getCDFparams(cdf, 'Timestamp')
Parameter Timestamp ms 
array([datetime.datetime(2017, 2, 1, 0, 0, 0, 999000),
       datetime.datetime(2017, 2, 1, 0, 0, 0, 999000),
       datetime.datetime(2017, 2, 1, 0, 0, 0, 999000), ...,
       datetime.datetime(2017, 2, 1, 23, 59, 59, 989000),
       datetime.datetime(2017, 2, 1, 23, 59, 59, 989000),
       datetime.datetime(2017, 2, 1, 23, 59, 59, 989000)], dtype=object)
```

**Comment by miktoki** [comment]
You're right, there were some issues with reading scalars from the products, which has now been updated.
